const DJ_CATELIST = 'DJ_CATELIST'
const CHOOSEN_DJRADIO = 'CHOOSEN_DJRADIO'
const PERFECT_NEW_RADIO = 'PERFECT_NEW_RADIO'
const DJ_RADIOS = 'DJ_RADIOS'
const TOTAL_PAGE = 'TOTAL_PAGE'
const CURRENT_PAGE = 'CURRENT_PAGE'

const obj = {
    DJ_CATELIST,
    CHOOSEN_DJRADIO,
    PERFECT_NEW_RADIO,
    DJ_RADIOS,
    TOTAL_PAGE,
    CURRENT_PAGE,
}

export default obj