const CHANGE_SELECTED_TITLE = 'CHANGE_SELECTED_TITLE'
const BANNER_CHANGE = 'BANNER_CHANGE'
const HOT_RECOMMEND = 'HOT_RECOMMEND'
const NEW_ALBUM = 'NEW_ALBUM'
const TOP_UP_LIST = 'TOP_UP_LIST'
const TOP_NEW_LIST = 'TOP_NEW_LIST'
const TOP_ORIGIN_LIST = 'TOP_ORIGIN_LIST'
const RESIDENT_SINGER = 'RESIDENT_SINGER'

export {
    CHANGE_SELECTED_TITLE,
    BANNER_CHANGE,
    HOT_RECOMMEND,
    NEW_ALBUM,
    TOP_UP_LIST,
    TOP_NEW_LIST,
    TOP_ORIGIN_LIST,
    RESIDENT_SINGER,
}