const CHOOSEN_SINGER = 'CHOOSEN_SINGER'
const CHOOSEN_ITEM = 'CHOOSEN_ITEM'
const RIGHT_MIDDLE_ISSHOW = 'RIGHT_MIDDLE_ISSHOW'
const ARTIST_LIST = 'ARTIST_LIST'
const TYPE = 'TYPE'
const AREA = 'AREA'
const INITIAL = 'INITIAL'

const obj = {
    CHOOSEN_SINGER,
    CHOOSEN_ITEM,
    RIGHT_MIDDLE_ISSHOW,
    ARTIST_LIST,
    TYPE,
    AREA,
    INITIAL,
}

export default obj