const ALL_SONGS_SORT = 'ALL_SONGS_SORT'
const CURRENT_CATEGORY = 'CURRENT_CATEGORY'
const CATEGORY_DETAIL = 'CATEGORY_DETAIL'
const TOTAL_PAGE = 'TOTAL_PAGE'
const CURRENT_PAGE = 'CURRENT_PAGE'

const obj = {
    ALL_SONGS_SORT,
    CURRENT_CATEGORY,
    CATEGORY_DETAIL,
    TOTAL_PAGE,
    CURRENT_PAGE,
}

export default obj