const PLAY_LIST = 'PLAY_LIST'
const CURRENT_PLAY_INDEX = ' CURRENT_PLAY_INDEX'
const PLAY_METHODS = 'PLAY_METHODS'
const AUTO_PLAY = 'AUTO_PLAY'
const SONGS_TOTAL_TIME = 'SONGS_TOTAL_TIME'
const COLLECTION_DETAIL_LIST = 'COLLECTION_DETAIL_LIST'
const LYRIC = 'LYRIC'

const obj = {
    PLAY_LIST,
    CURRENT_PLAY_INDEX,
    PLAY_METHODS,
    AUTO_PLAY,
    SONGS_TOTAL_TIME,
    COLLECTION_DETAIL_LIST,
    LYRIC,
}

export default obj